import {StyleSheet, Platform} from 'react-native';
import colors from '../../assets/colors/colors';

const styles = StyleSheet.create({
  mainModal: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: -25,
  },
  containerContentOrder: {
    height: 650,
    width: '100%',
    backgroundColor: colors.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 25.35,
    elevation: 19,
  },
  headerCodeOrder: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 23,
    lineHeight: 27,
  },
  itemMenuListScroll: {
    height: 300,
    width: '100%',
    marginTop: 12.5,
  },
  menuItemContainer: {
    height: 115,
    width: '100%',
    marginBottom: 25,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemImage: {
    height: 112,
    width: 112,
    backgroundColor: colors.borderGrey,
    borderRadius: 16,
  },
  nameItemText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  otherTextStyle: {
    width: '65%',
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
  },
  detailInfoContainer: {
    height: '80%',
    width: '100%',
    justifyContent: 'space-between',
    marginLeft: 16,
  },
  noteContainer: {
    height: 55,
    width: '100%',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  buttonBottomContainer: {
    marginTop: 25,
    height: 140,
    width: '100%',
    marginBottom: 25,
  },
  followButton: {
    height: 64,
    width: '100%',
    backgroundColor: colors.borderGrey,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    height: 64,
    width: '100%',
    backgroundColor: colors.pink,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  endPayText: {
    color: colors.pinkText,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  textInButton: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  textInButtonCancel: {
    color: colors.pinkText,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  modalCancelContainer: {
    flex: 1,
    backgroundColor: '#000000aa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelContainer: {
    backgroundColor: colors.white,
    width: '70%',
    height: 290,
    borderRadius: 24,
    padding: 40,
  },
  headerTextModal: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 26,
  },
  buttonCancel: {
    height: 64,
    width: '100%',
    borderRadius: 16,
    backgroundColor: colors.buttonBackGroundColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 8,
  },
  leaveButton: {
    height: 64,
    width: '100%',
    borderRadius: 16,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelText: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22.5,
  },
  leaveText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22.5,
  },
});

export default styles;
