import { StyleSheet } from 'react-native';
import colors from '../../../../assets/colors/colors';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  mainContentContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
    marginHorizontal: 16,
  },
  mainContentScroll: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  delivetyTimeContainer: {
    width: '100%',
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryTimeText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
    textAlign: 'center',
  },
  titleContainer: {
    height: 45,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleLogo: {
    width: 32,
    height: 32,
    borderRadius: 50,
  },
  favoritesImageRes: {
    width: 32,
    height: 32,
    borderRadius: 50,
    marginRight: 12,
  },
  titleText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 20,
    lineHeight: 26,
    textAlign: 'center',
    marginLeft: 12,
  },
  totalAmount: {
    height: 70,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amountText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 20,
    lineHeight: 26,
    textAlign: 'center',
  },
  amountNumber: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    textAlign: 'center',
  },
  containerProButton: {
    height: 125,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginBottom: 20,
  },
  promoContainer: {
    width: '100%',
    height: 70,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInputPromo: {
    height: 64,
    width: '70%',
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    backgroundColor: colors.white,
    paddingLeft: 20,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    padding: 0,
  },
  buttonApplyPromo: {
    minHeight: 64,
    width: '30%',
    backgroundColor: colors.borderGrey,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  applyTextInButton: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    textAlign: 'center',
  },
  containerItemMenu: {
    height: 112,
    width: '100%',
    flexDirection: 'row',
    marginTop: 16,
    justifyContent: 'space-between',
  },
  imageContainer: {
    height: 112,
    width: 112,
    borderRadius: 18,
    backgroundColor: colors.borderGrey,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  menuItemImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  containerRight: {
    height: '100%',
    width: '65%',
    justifyContent: 'space-between',
  },
  containerRightWithBut: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  changeButton: {
    height: 40,
    width: 40,
    borderRadius: 12,
    backgroundColor: colors.buttonBackGroundColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leftTwoButtonContainer: {
    height: 44,
    width: 134,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemTittle: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  itemPrice: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19,
    marginTop: 5,
  },
  itemNumber: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  underCartIconText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 24,
    lineHeight: 30,
    marginTop: 25,
    marginBottom: 45,
  },
  emptyBasketContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    height: 30,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: colors.buttonBackGroundColor,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 18,
  },
  indicatorContainer: {
    flex: 1,
    height: 100,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  amountContainer: {
    flex: 1,
    marginTop: 32,
    borderTopWidth: 1,
    borderColor: colors.borderGrey,
    marginHorizontal: 16,
  },
  proceedContainer: {},
});

export default styles;
