import {StyleSheet} from 'react-native';
import colors from '../../../../assets/colors/colors';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  mainContentContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
    marginHorizontal: 16,
    marginBottom: 70,
  },
  mainContentScroll: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  mainFilterTouch: {
    height: '100%',
    flexDirection: 'row',
    marginLeft: 18,
    alignItems: 'flex-start',
  },
  containerFilter: {
    width: 107,
    height: 44,
    borderRadius: 50,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
  },
  mainContainerFavItem: {
    minHeight: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  restrauntContainer: {
    height: 180,
    width: '100%',
    borderRadius: 25,
  },
  logoRestraunt: {
    height: 134,
    width: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  imageContainerStyle: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  bottomElement: {
    height: 50,
    width: '100%',
    backgroundColor: colors.white,
    borderBottomEndRadius: 25,
    borderBottomLeftRadius: 25,
    padding: 14,
    flexDirection: 'row',
  },
  generalDistanceText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 17,
    lineHeight: 22.5,
  },
  distanceText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  subElementContainer: {
    height: 30,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  subElement: {
    minHeight: 18,
    minWidth: 60,
    borderRadius: 50,
    backgroundColor: colors.backGroundBrown,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  elementText: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 18,
  },
  indicatorContainer: {
    flex: 1,
    height: 100,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerRestFav: {
    height: 45,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  favoritesImageRes: {
    width: 32,
    height: 32,
    borderRadius: 50,
    marginRight: 12,
  },
  menuFavContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  restrauntName: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 20,
    lineHeight: 26,
  },
  buttonCartContainer: {
    height: 114,
    width: '100%',
    backgroundColor: colors.white,
    position: 'absolute',
    bottom: 0,
    marginBottom: -30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  buttonContainerCart: {
    height: 64,
    width: '80%',
    backgroundColor: colors.buttonBackGroundColor,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonContainerDelete: {
    height: 64,
    width: 64,
    borderRadius: 16,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainTextView: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  containerMap: {
    height: '90%',
    width: '90%',
    borderRadius: 30,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  mapStyle: {
    height: '100%',
    width: '100%',
    borderRadius: 30,
    marginHorizontal: 16,
  },
});

export default styles;
