import {StyleSheet} from 'react-native';
import colors from '../../assets/colors/colors';

const styles = StyleSheet.create({
  mainModal: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: '#000000aa',
    marginBottom: -25,
  },
  containerViewDis: {
    minHeight: 20,
  },
  containerInfoContent: {
    minHeight: 344,
    width: '100%',
    backgroundColor: colors.backAddress,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 22,
  },
  headerContainer: {
    minHeight: 45,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  resNameContainer: {
    height: '100%',
    width: '55%',
  },
  nameText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 32,
    lineHeight: 36.5,
  },
  distanceText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  buttonTypeContainer: {
    height: 36,
    minWidth: 78,
    backgroundColor: colors.textDarkGrey,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
  },
  addressResText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  workTimeText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
  },
  subElementContainer: {
    minHeight: 40,
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 24,
  },
  subElement: {
    minHeight: 18,
    minWidth: 60,
    borderRadius: 50,
    backgroundColor: colors.backGroundBrown,
    marginRight: 8,
    marginBottom: 8,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  elementText: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 18,
  },
  infoText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
  },
});

export default styles;
