import {StyleSheet} from 'react-native';
import colors from '../../assets/colors/colors';

const styles = StyleSheet.create({
  bottomDrawerSections: {
    marginBottom: 30,
  },
  mainNavigationContainer: {
    marginLeft: 15,
  },
  menuElementTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 40,
  },
  mainNavigationText: {
    color: colors.textDarkGrey,
    marginLeft: 15,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  userInfoContainer: {
    width: '90%',
    height: 50,
    marginTop: 35,
    marginLeft: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nameText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 20,
    lineHeight: 26,
  },
  emailText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 18,
  },
  swapAccount: {
    width: 140,
    height: 40,
    marginLeft: 15,
    marginTop: 16,
    borderRadius: 12,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swapAccountText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
  },
  logOutContainer: {width: '100%', marginLeft: 15},
  logOutTouch: {flexDirection: 'row', alignItems: 'center'},
  logOutText: {
    color: colors.textDarkGrey,
    marginLeft: 15,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
  modalApproveContainer: {
    flex: 1,
    backgroundColor: '#000000aa',
    justifyContent: 'center',
    alignItems: 'center',
  },
  approveContainer: {
    backgroundColor: colors.white,
    width: '75%',
    height: 340,
    borderRadius: 24,
    padding: 40,
    alignItems: 'center',
  },
  headerTextModal: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 20,
    lineHeight: 26,
  },
  containerButton: {
    width: '100%',
    height: '65%',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 15,
  },
  buttonStyleSwap: {
    height: 40,
    width: '100%',
    backgroundColor: colors.buttonBackGroundColor,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  buttonStyleSkip: {
    height: 40,
    width: '100%',
    backgroundColor: '#154A86',
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInButton: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 15,
    lineHeight: 18,
  },
  textCancelStyle: {
    color: colors.buttonBackGroundColor,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 19,
  },
});

export default styles;
