import {StyleSheet} from 'react-native';

import colors from '../../../../assets/colors/colors';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
    marginHorizontal: 16,
    marginTop: 3,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  mainOrderContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  headerOrderContainer: {
    width: '100%',
    height: 35,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderHeaderText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope-SemiBold',
    fontStyle: 'normal',
    fontSize: 24,
    lineHeight: 30,
  },
  mapButtoText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  restrauntListContainer: {
    minHeight: 50,
    width: '100%',
    marginTop: 20,
    flexDirection: 'row',
  },
  circlePoint: {
    width: 32,
    height: 32,
    backgroundColor: colors.borderGrey,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -3,
  },
  numberInPoint: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
  },
  progressContainer: {
    width: 32,
    minHeight: 32,
    alignItems: 'center',
  },
  allResrtraunList: {
    minHeight: 30,
    width: '100%',
  },
  restrauntProgresList: {
    width: '88%',
    height: 75,
    marginLeft: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
  customerPoint: {
    width: '88%',
    height: 50,
    marginLeft: 12,
    marginBottom: 30,
  },
  restrauntNameText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope-SemiBold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  distanceNumber: {
    color: colors.backGroundBrown,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  detailInfoText: {
    color: colors.backGroundBrown,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
    marginTop: 5,
  },
  detailsInfoButton: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deliveryTypeContainer: {
    height: 40,
    width: '100%',
  },
  textDeliveryType: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope-SemiBold',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 18,
  },
  textMainType: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.5,
  },
  borderBottomLine: {
    borderWidth: 1,
    borderColor: colors.borderGrey,
    marginTop: 20,
    marginBottom: 20,
  },
  timeAndIncomeContainer: {
    width: '100%',
    height: 40,
    flexDirection: 'row',
  },
  timeContainer: {
    width: '60%',
    height: '100%',
  },
  incomeContainer: {
    width: '40%',
    height: '100%',
  },
  headerText: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 18,
  },
  contentText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
    marginTop: 3,
  },
  clientInfoContainer: {
    height: 80,
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    justifyContent: 'space-between',
  },
  nameClientText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope-SemiBold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  typeClientText: {
    color: colors.backGroundBrown,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
  },
  cancelOrderButton: {
    height: 65,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
  },
  bottomTwoButtons: {
    height: 30,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  cancelText: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope-SemiBold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
});

export default styles;
