import {StyleSheet} from 'react-native';

import colors from '../../../../../assets/colors/colors';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
    marginHorizontal: 16,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  buttonContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 25,
    marginTop: 15,
  },
  headerText: {
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  textInput: {
    minHeight: 108,
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    marginTop: 24,
    padding: 20,
    paddingTop: 20,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
    textAlignVertical: 'top',
  },
  addAddressContainer: {
    height: 64,
    width: '100%',
    backgroundColor: colors.backGroundMainColor,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: colors.borderGrey,
    marginTop: 16,
    marginBottom: 20,
  },
  contentAddContainer: {
    width: '100%',
    height: '100%',
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textButtonAdd: {
    marginLeft: 11,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 20.5,
    color: colors.textDarkGrey,
  },
  containerItemScroll: {
    flex: 1,
    flexDirection: 'row',
  },
  imageContainer: {
    height: 60,
    width: 60,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: colors.borderGrey,
  },
  borderStyle: {
    borderBottomWidth: 1,
    borderColor: colors.borderGrey,
    marginTop: 24,
    marginBottom: 24,
  },
  oderNumberHeader: {
    fontFamily: 'Manrope-SemiBold',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 20,
    lineHeight: 26.5,
    color: colors.textDarkGrey,
    marginBottom: 16,
  },
  totalAmountStyle: {
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.5,
    color: colors.textLightBrown,
    marginTop: 8,
  },
  smallPlusButton: {
    width: 60,
    height: 60,
    backgroundColor: colors.borderGrey,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: 5,
  },
  mainContainerWithImage: {
    flexDirection: 'row',
    width: '100%',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 20,
  },
  imageAddContainer: {
    height: 70,
    width: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageStyle: {width: 60, height: 60, borderRadius: 10},
  cancelPhotoButton: {
    position: 'absolute',
    right: 0,
    top: 0,
  },
  noneContainer: {
    flex: 1,
    alignItems: 'center',
    top: '25%',
  },
  noneText: {
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 24,
    lineHeight: 30,
    textAlign: 'center',
    marginTop: 24,
  },
  errorContainer: {
    marginLeft: 20,
    marginTop: 10,
  },
  errorInput: {
    color: colors.buttonBackGroundColor,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontSize: 12,
    lineHeight: 15,
  },
});

export default styles;
