import {StyleSheet, Platform} from 'react-native';
import colors from '../../../../assets/colors/colors';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
    marginHorizontal: 16,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.backGroundMainColor,
  },
  oneLinesDetails: {
    height: 60,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: colors.borderGrey,
  },
  leftContainerLine: {
    width: '50%',
    justifyContent: 'center',
  },
  rightContainerLine: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftTextContainer: {
    width: '85%',
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  rightTextNearArrow: {
    width: '85%',
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.6,
    textAlign: 'right',
  },
  headerTextType: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.4,
  },
  deliveryTypeContainer: {
    minHeight: 100,
    marginTop: 24,
  },
  leftContainer: {
    height: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioContainer: {
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  deliveryContainer: {
    height: 45,
    width: '70%',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.buttonBackGroundColor,
    marginTop: 15,
  },
  textStyle: {
    width: '86%',
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    color: colors.textDarkGrey,
    marginLeft: 16,
  },
  backButton: {
    marginTop: 20,
  },
  textHeaderModal: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 32,
    lineHeight: 38.4,
    color: colors.textDarkGrey,
  },
  navigationContainer: {
    height: 25,
    width: '100%',
    flexDirection: 'row',
    marginBottom: 30,
    alignItems: 'center',
    marginTop: Platform.OS === 'android' ? 20 : 0,
  },
  navigationButton: {
    height: 25,
    width: '10%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  navigationTextContainer: {
    height: '100%',
    width: '85%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigationTitle: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    textAlign: 'center',
    color: colors.textDarkGrey,
  },
  dropTouchContainer: {
    flexDirection: 'row',
    height: '100%',
    width: '70%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextDropDown: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  leftContainerAddress: {
    width: '80%',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  radioContainerAddress: {
    width: '20%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  paymentContainer: {
    height: 80,
    width: '100%',
    backgroundColor: colors.backAddress,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#fff',
    marginTop: 15,
  },
  textHeaderAddress: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    color: colors.textDarkGrey,
  },
  cityTextStyle: {
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.5,
    color: colors.textDarkGrey,
  },
  addAddressContainer: {
    height: 64,
    width: '100%',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: colors.borderGrey,
    marginTop: 16,
    marginBottom: 25,
  },
  contentAddContainer: {
    width: '100%',
    height: '100%',
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textButtonAdd: {
    marginLeft: 11,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 20.5,
    color: colors.textDarkGrey,
  },
  allPaymentContainer: {
    minHeight: 85,
    width: '100%',
    marginTop: 15,
    justifyContent: 'space-between',
  },
  leftContainerPayment: {
    width: '80%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioContainerPayment: {
    width: '20%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  paymentContainerModal: {
    width: '100%',
    height: 64,
    backgroundColor: colors.backAddress,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#fff',
    marginTop: 16,
  },
  textStylePay: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    color: colors.textDarkGrey,
  },
  timeButtonContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 30,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorInput: {
    color: colors.buttonBackGroundColor,
    fontFamily: 'Manrope',
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 19,
    textAlign: 'center',
  },
});

export default styles;
