import {StyleSheet, Platform} from 'react-native';
import colors from '../../assets/colors/colors';

import * as dimensions from '../../dimensionConfig';

const styles = StyleSheet.create({
  mainModal: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: '#000005aa',
    opacity: Platform.OS === 'android' ? 0.1 : 0.5,
    marginBottom: -25,
  },
  containerInfoContent: {
    minHeight: 344,
    width: '100%',
    maxHeight: dimensions.height < 600 ? 440 : 700,
    backgroundColor: colors.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  imageAllContainer: {
    height: dimensions.height < 600 ? 190 : 340,
    width: '100%',
    backgroundColor: colors.backAddress,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  imageContainer: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuItemImage: {
    height: dimensions.height < 600 ? 132 : 242,
    width: dimensions.height < 600 ? 150 : 260,
  },
  bottomContainer: {
    minHeight: 20,
    width: '100%',
    backgroundColor: colors.white,
    padding: 16,
  },
  titlePriceContainer: {
    minHeight: 40,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leftContainer: {
    width: '70%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  rightContainer: {
    width: '30%',
    alignItems: 'flex-end',
  },
  burgerName: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: dimensions.height < 600 ? 17 : 20,
    lineHeight: dimensions.height < 600 ? 20 : 23,
    flexGrow: 1,
  },
  weightItem: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: dimensions.height < 600 ? 12 : 14,
    lineHeight: dimensions.height < 600 ? 17 : 19.5,
    marginLeft: 8,
  },
  textInfo: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: dimensions.height < 600 ? 13 : 14,
    lineHeight: dimensions.height < 600 ? 15 : 19.5,
  },
  containerButton: {
    height: 35,
    width: '100%',
    justifyContent: 'center',
  },
  moreInfoButton: {
    height: 30,
    width: '40%',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: dimensions.height < 600 ? 5 : 15,
  },
  textButton: {
    color: colors.buttonBackGroundColor,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: dimensions.height < 600 ? 12 : 14,
    lineHeight: dimensions.height < 600 ? 17 : 19.5,
  },
  containerBottomButtons: {
    height: dimensions.height < 600 ? 55 : 75,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: dimensions.height < 600 ? 5 : 20,
  },
  leftButtonContainer: {
    height: dimensions.height < 600 ? 44 : 64,
    width: dimensions.height < 600 ? 140 : 166,
    backgroundColor: colors.borderGrey,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: dimensions.height < 600 ? 10 : 20,
  },
  rightButtonContainer: {
    height: 64,
    width: 166,
    backgroundColor: colors.buttonBackGroundColor,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInButton: {
    color: colors.white,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: dimensions.height < 600 ? 15 : 17,
    lineHeight: dimensions.height < 600 ? 20 : 22.4,
  },
  valueStyle: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 22.4,
  },
  dropContainer: {
    minHeight: 45,
    width: '100%',
    marginTop: dimensions.height < 600 ? 5 : 10,
  },
  moreInfoContainer: {
    height: dimensions.height < 600 ? 52 : 72,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.borderGrey,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tableItem: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  numberUpStyle: {
    color: colors.textDarkGrey,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: dimensions.height < 600 ? 14 : 16,
    lineHeight: dimensions.height < 600 ? 20 : 22.4,
  },
  numberBottomStyle: {
    color: colors.textLightBrown,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: 'normal',
    fontSize: dimensions.height < 600 ? 12 : 14,
    lineHeight: dimensions.height < 600 ? 17 : 19.5,
  },
  likeIcon: {
    backgroundColor: colors.white,
    width: 40,
    height: 40,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 16,
    top: 16,
  },
});

export default styles;
