import {StyleSheet, Platform} from 'react-native';
import colors from '../../assets/colors/colors';

const styles = StyleSheet.create({
  headerContainer: {
    height: 70,
    width: '100%',
    justifyContent: 'flex-end',
    marginBottom: 20,
  },
  backButton: {
    marginTop: 20,
  },
  textHeaderModal: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 32,
    lineHeight: 38.4,
    color: colors.textDarkGrey,
  },
  navigationContainer: {
    height: 25,
    width: '100%',
    flexDirection: 'row',
    marginBottom: 30,
    alignItems: 'center',
    marginTop: Platform.OS === 'android' ? 20 : 0,
  },
  navigationButton: {
    height: 25,
    width: '10%',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  navigationTextContainer: {
    height: '100%',
    width: '85%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigationTitle: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    textAlign: 'center',
    color: colors.textDarkGrey,
  },
  dropTouchContainer: {
    flexDirection: 'row',
    height: '100%',
    width: '70%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTextDropDown: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },

  leftContainer: {
    width: '80%',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  radioContainer: {
    width: '20%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  paymentContainer: {
    height: 80,
    width: '100%',
    backgroundColor: colors.backAddress,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#fff',
    marginTop: 15,
  },
  textHeaderAddress: {
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
    color: colors.textDarkGrey,
  },
  textStyle: {
    fontFamily: 'Manrope',
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 19.5,
    color: colors.textDarkGrey,
  },
  addAddressContainer: {
    height: 64,
    width: '100%',
    backgroundColor: colors.white,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: colors.borderGrey,
    marginTop: 16,
    marginBottom: 25,
  },
  contentAddContainer: {
    width: '100%',
    height: '100%',
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textButtonAdd: {
    marginLeft: 11,
    fontFamily: 'Manrope',
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 20.5,
    color: colors.textDarkGrey,
  },
  goOnlineContainer: {
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  textOnline: {
    color: colors.textDarkGrey,
    marginRight: 10,
    fontFamily: 'Manrope',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22.5,
  },
});

export default styles;
