//Sign up type
export const SET_USER_CLASS = 'SET_USER_CLASS';
export const SET_PHONE = 'SET_PHONE';
export const SET_RES_POST_PHONE = 'SET_RES_POST_PHONE';
export const SET_RES_POST_CODE = 'SET_RES_POST_CODE';
export const SET_RES_TOKEN = 'SET_RES_TOKEN';
export const SET_TYPE_USER = 'SET_TYPE_USER';
export const SET_INITED = 'SET_INITED';
export const SET_MESSAGE = 'SET_MESSAGE';
//Sign up form
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_DATE_OF_BIRTH = 'SET_DATE_OF_BIRTH';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_CITY = 'SET_CITY';
export const SET_RES_POST_SIGN_UP_FORM = 'SET_RES_POST_SIGN_UP_FORM';
export const SET_ALL_STATE = 'SET_ALL_STATE';
export const SET_ALL_CITY = 'SET_ALL_CITY';
export const SET_ID_STATE = 'SET_ID_STATE';
export const SET_CITY_ID = 'SET_CITY_ID';
export const SET_RES_UPDATE = 'SET_RES_UPDATE';
export const SET_RES_SWITCH = 'SET_RES_SWITCH';
//async storage
export const SET_ASYNC_TOKEN = 'SET_ASYNC_TOKEN';
export const SET_ASYNC_TYPE = 'SET_ASYNC_TYPE';
export const SET_ASYNC_ROLE = 'SET_ASYNC_ROLE';
//profile
export const SET_RES_PROFILE = 'SET_RES_PROFILE';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_CHANGE_NAVIGATION = 'SET_CHANGE_NAVIGATION';
export const SET_MODAL_FULL_INFO = 'SET_MODAL_FULL_INFO';
//restraunts
export const SET_ALL_RESTRAUNT = 'SET_ALL_RESTRAUNT';
export const SET_RES_RESTRAUNT = 'SET_RES_RESTRAUNTS';
export const SET_FILTER_BUTTON = 'SET_FILTER_BUTTON';
export const SET_SINGLE_RESTRAUNT = 'SET_SINGLE_RESTRAUNT';
export const SET_FULL_RESTRAUNT_INFO = 'SET_FULL_RESTRAUNT_INFO';
export const SET_ALL_FAVORITES = 'SET_ALL_FAVORITES';
export const SET_NUMBER_OF_FOOD = 'SET_NUMBER_OF_FOOD';
export const SET_RESTAURANT_LOADED = 'SET_RESTAURANT_LOADED';
//address
export const SET_LIST_ADDRESS = 'SET_LIST_ADDRESS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_RES_DEFAULT_ADDRESS = 'SET_RES_DEFAULT_ADDRESS';
//menu item
export const SET_LIKE_MENU_ITEM = 'SET_LIKE_MENU_ITEM';
export const SET_MENU_ITEM_FROM_RES = 'SET_MENU_ITEM_FROM_RES';
export const SET_LIKE_ITEM = 'SET_LIKE_ITEM';
export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const SET_ITEM_MENU_BY_CATEGORY = 'SET_ITEM_MENU_BY_CATEGORY';
export const SET_DELETE_ITEM_FROM_MAIN_FAVORITES =
  'SET_DELETE_ITEM_FROM_MAIN_FAVORITES';
export const SET_RESPONSE_FAV = 'SET_RESPONSE_FAV';
//cart
export const SET_RES_PROMO = 'SET_RES_PROMO';
export const SET_PROMO_CODE = 'SET_PROMO_CODE';
export const SET_ALL_CART_ITEM = 'SET_ALL_CART_ITEM';
export const SET_RES_SET_IN_CART = 'SET_RES_SET_IN_CART';
export const SET_COPY_ALL_CART = 'SET_COPY_ALL_CART';
export const SET_RES_GET_CART = 'SET_RES_GET_CART';
export const SET_CATEGORY_IDS = 'SET_CATEGORY_IDS';
export const SET_FULL_SUM = 'SET_FULL_SUM';
export const SET_FULL_ITEM_FAV_MODAL = 'SET_FULL_ITEM_FAV_MODAL';
export const SET_CART_LOAD = 'SET_CART_LOAD';
export const SET_CLEAR_FILTER = 'SET_CLEAR_FILTER';
//order
export const SET_ALL_ORDERS = 'SET_ALL_ORDERS';
export const SET_RES_PROCEED_ORDER = 'SET_RES_PROCEED_ORDER';
export const SET_DELIVERY_TYPE = 'SET_DELIVERY_TYPE';
export const SET_LIST_CREDIT_CARD = 'SET_LIST_CREDIT_CARD';
export const SET_RES_DELIVERY_TIME = 'SET_RES_DELIVERY_TIME';
export const SET_RES_CONFIRM_ORDER = 'SET_RES_CONFIRM_ORDER';
export const SET_RES_DATA_SIMPLE_ORDER = 'SET_RES_DATA_SIMPLE_ORDER';
export const SET_RES_CANCEL_ORDER = 'SET_RES_CANCEL_ORDER';
export const SET_FULL_ADD_ADDRESS = 'SET_FULL_ADD_ADDRESS';
export const SET_CARD_NAME = 'SET_CARD_NAME';
export const SET_TOTAL_PRICES = 'SET_TOTAL_PRICES';
export const SET_DELIVERY_TRACK_TIME = 'SET_DELIVERY_TRACK_TIME';
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_ORDER_DELIVERY_TRACK_TIME = 'SET_ORDER_DELIVERY_TRACK_TIME';
export const SET_ORDER_COURIER = 'SET_ORDER_COURIER';
//add credit card
export const SET_CARD_NUMBER = 'SET_CARD_NUMBER';
export const SET_CARD_HOLDER_NAME = 'SET_CARD_HOLDER_NAME';
export const SET_EXPIRY_DATE = 'SET_EXPIRY_DATE';
export const SET_CVV = 'SET_CVV';
export const SET_SAVE_CARD = 'SET_SAVE_CARD';
export const SET_RES_ADD_CARD = 'SET_RES_ADD_CARD';
export const SET_ONE_TIME_CARD = 'SET_ONE_TIME_CARD';
export const SET_RES_DELETE_CARD = 'SET_RES_DELETE_CARD';
export const SET_RES_DEFAUL_CARD = 'SET_RES_DEFAUL_CARD';
export const SET_RES_LIST_DEFAULT_CARD = 'SET_RES_LIST_DEFAULT_CARD';
export const SET_PAY_NAME = 'SET_PAY_NAME';
//add address from form
export const SET_ADDRESS_CITY = 'SET_ADDRESS_CITY';
export const SET_ADDRESS_STREET_NAME = 'SET_ADDRESS_STREET_NAME';
export const SET_ADDRESS_APPARTMENT = 'SET_ADDRESS_APPARTMENT';
export const SET_ADDRESS_COMMENT = 'SET_ADDRESS_COMMENT';
export const SET_RES_ADD_ADDRESS_DELIVERY = 'SET_RES_ADD_ADDRESS_DELIVERY';
export const SET_FINALLY_DELIVERY_TIME = 'SET_FINALLY_DELIVERY_TIME';
export const SET_CLEAR_ALL_MAIN = 'SET_CLEAR_ALL_MAIN';
export const SET_ADDRESS_LABEL = 'SET_ADDRESS_LABEL';
export const SET_RES_DELETE_ADDRESS = 'SET_RES_DELETE_ADDRESS';
export const SET_MODAL_HEADER_NAV = 'SET_MODAL_HEADER_NAV';
export const SET_INFO_ONE_ADDRESS = 'SET_INFO_ONE_ADDRESS';
export const SET_RES_ADDRESS_UPDATE = 'SET_RES_ADDRESS_UPDATE';
export const SET_GEO_INFO = 'SET_GEO_INFO';
//Contact us
export const SET_VISIBLE_CONTACT = 'SET_VISIBLE_CONTACT';
export const SET_RES_LAST_ORDER = 'SET_RES_LAST_ORDER';
export const SET_ALL_FAQ = 'SET_ALL_FAQ';
//Change
export const SET_WAIT_SWAP = 'SET_WAIT_SWAP';
export const SET_RES_ONE_TIME_ADDRESS = 'SET_RES_ONE_TIME_ADDRESS';
export const SET_RES_SWITCH_CREATE = 'SET_RES_SWITCH_CREATE';
export const SET_INFO_CHANGE_ACCOUNT = 'SET_INFO_CHANGE_ACCOUNT';
export const SET_START_HANDLE_SWITCH = 'SET_START_HANDLE_SWITCH';
//start work driver
export const SET_DRIVER_ONLINE = 'SET_DRIVER_ONLINE';
export const SET_START_WORK_MODAL = 'SET_START_WORK_MODAL';
export const SET_END_WORK_MODAL = 'SET_END_WORK_MODAL';
export const SET_RES_END_WORK = 'SET_RES_END_WORK';
export const SET_RES_STOP_WORK = 'SET_RES_STOP_WORK';
export const SET_DRIVER_CONFIRMED = 'SET_DRIVER_CONFIRMED';
//driver payments
export const SET_DRIVER_AMOUNT_CARD = 'SET_DRIVER_AMOUNT_CARD';
export const SET_DRIVER_CARD_NUMBER = 'SET_DRIVER_CARD_NUMBER';
export const SET_DRIVER_CARDHOLDER_NAME = 'SET_DRIVER_CARDHOLDER_NAME';
export const SET_RES_WITHDRAW = 'SET_RES_WITHDRAW';
export const SET_KYC_LINK = 'SET_KYC_LINK';
//notification
export const SET_ALL_NOTIFICATIONS = 'SET_ALL_NOTIFICATIONS';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_RATE_ORDER_ID = 'SET_RATE_ORDER_ID';
//driver order
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const SET_ALL_INFO_ORDER = 'SET_ALL_INFO_ORDER';
export const SET_ALL_DETAIL_INFO = 'SET_ALL_DETAIL_INFO';
export const SET_DRIVER_ORDER_HISTORY = 'SET_DRIVER_ORDER_HISTORY';
export const SET_RES_CANCEL_ORDER_DRIVER = 'SET_RES_CANCEL_ORDER_DRIVER';
export const SET_ALL_DETAIL_CURRENT_ORDER = 'SET_ALL_DETAIL_CURRENT_ORDER';
export const SET_CURRENT_ORDER_MESSAGE = 'SET_CURRENT_ORDER_MESSAGE';
export const SET_END_ORDER = 'SET_END_ORDER';
export const SET_TRIGER_ORDER_READY = 'SET_TRIGER_ORDER_READY';
export const SET_CLEAR_DATA_END_ORDER = 'SET_CLEAR_DATA_END_ORDER';
export const SET_SEPARATE_RESTORAN = 'SET_SEPARATE_RESTORAN';
export const SET_ACCEPT_ORDER = 'SET_ACCEPT_ORDER';
export const SET_DRIVER_POSITION = 'SET_DRIVER_POSITION';
//navigation route
export const SET_NAVIGATION_ROUTE = 'SET_NAVIGATION_ROUTE';
export const SET_NAVIGATION_ROUTE_ADDRESS = 'SET_NAVIGATION_ROUTE_ADDRESS';
export const SET_DEEP_LINK = 'SET_DEEP_LINK';
//rate order
export const SET_MODAL_RATE = 'SET_MODAL_RATE';
export const SET_GET_DATA_RATE = 'SET_GET_DATA_RATE';
// stripe
export const SET_STRIPE_PUB_KEY = 'SET_STRIPE_PUB_KEY';
export const SET_CONFIRM_ORDER_PAY = 'SET_CONFIRM_ORDER_PAY';
// handling Internet and Server connection
export const SET_RES_PRODILE_STATUS_CODE_POSITIVE =
  'SET_RES_PRODILE_STATUS_CODE_POSITIVE';
export const SET_RES_PRODILE_STATUS_CODE_NEGATIVE =
  'SET_RES_PRODILE_STATUS_CODE_NEGATIVE';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_RESTRICTED_STATUS = 'SET_RESTRICTED_STATUS';
